#/bin/bash
cp rgba_16_should_be_rgba_16.png interlaced_rgba_16_should_be_rgba_16.png
cp rgba_16_should_be_rgba_8.png interlaced_rgba_16_should_be_rgba_8.png
cp rgba_8_should_be_rgba_8.png interlaced_rgba_8_should_be_rgba_8.png
cp rgba_16_should_be_rgb_16.png interlaced_rgba_16_should_be_rgb_16.png
cp rgba_16_should_be_rgb_8.png interlaced_rgba_16_should_be_rgb_8.png
cp rgba_8_should_be_rgb_8.png interlaced_rgba_8_should_be_rgb_8.png
cp rgba_16_should_be_palette_8.png interlaced_rgba_16_should_be_palette_8.png
cp rgba_8_should_be_palette_8.png interlaced_rgba_8_should_be_palette_8.png
cp rgba_16_should_be_palette_4.png interlaced_rgba_16_should_be_palette_4.png
cp rgba_8_should_be_palette_4.png interlaced_rgba_8_should_be_palette_4.png
cp rgba_16_should_be_palette_2.png interlaced_rgba_16_should_be_palette_2.png
cp rgba_8_should_be_palette_2.png interlaced_rgba_8_should_be_palette_2.png
cp rgba_16_should_be_palette_1.png interlaced_rgba_16_should_be_palette_1.png
cp rgba_8_should_be_palette_1.png interlaced_rgba_8_should_be_palette_1.png
cp rgba_16_should_be_grayscale_alpha_16.png interlaced_rgba_16_should_be_grayscale_alpha_16.png
cp rgba_16_should_be_grayscale_alpha_8.png interlaced_rgba_16_should_be_grayscale_alpha_8.png
cp rgba_8_should_be_grayscale_alpha_8.png interlaced_rgba_8_should_be_grayscale_alpha_8.png
cp rgba_16_should_be_grayscale_16.png interlaced_rgba_16_should_be_grayscale_16.png
cp rgba_16_should_be_grayscale_8.png interlaced_rgba_16_should_be_grayscale_8.png
cp rgba_8_should_be_grayscale_8.png interlaced_rgba_8_should_be_grayscale_8.png
cp rgba_16_should_be_palette_4_grayscale.png interlaced_rgba_16_should_be_palette_4_grayscale.png
cp rgba_8_should_be_palette_4_grayscale.png interlaced_rgba_8_should_be_palette_4_grayscale.png
cp rgba_16_should_be_palette_2_grayscale.png interlaced_rgba_16_should_be_palette_2_grayscale.png
cp rgba_8_should_be_palette_2_grayscale.png interlaced_rgba_8_should_be_palette_2_grayscale.png
cp rgba_16_should_be_palette_1_grayscale.png interlaced_rgba_16_should_be_palette_1_grayscale.png
cp rgba_8_should_be_palette_1_grayscale.png interlaced_rgba_8_should_be_palette_1_grayscale.png
cp rgb_16_should_be_rgb_16.png interlaced_rgb_16_should_be_rgb_16.png
cp rgb_16_should_be_rgb_8.png interlaced_rgb_16_should_be_rgb_8.png
cp rgb_8_should_be_rgb_8.png interlaced_rgb_8_should_be_rgb_8.png
cp rgb_16_should_be_palette_8.png interlaced_rgb_16_should_be_palette_8.png
cp rgb_8_should_be_palette_8.png interlaced_rgb_8_should_be_palette_8.png
cp rgb_16_should_be_palette_4.png interlaced_rgb_16_should_be_palette_4.png
cp rgb_8_should_be_palette_4.png interlaced_rgb_8_should_be_palette_4.png
cp rgb_16_should_be_palette_2.png interlaced_rgb_16_should_be_palette_2.png
cp rgb_8_should_be_palette_2.png interlaced_rgb_8_should_be_palette_2.png
cp rgb_16_should_be_palette_1.png interlaced_rgb_16_should_be_palette_1.png
cp rgb_8_should_be_palette_1.png interlaced_rgb_8_should_be_palette_1.png
cp rgb_16_should_be_grayscale_16.png interlaced_rgb_16_should_be_grayscale_16.png
cp rgb_16_should_be_grayscale_8.png interlaced_rgb_16_should_be_grayscale_8.png
cp rgb_8_should_be_grayscale_8.png interlaced_rgb_8_should_be_grayscale_8.png
cp rgb_16_should_be_palette_4_grayscale.png interlaced_rgb_16_should_be_palette_4_grayscale.png
cp rgb_8_should_be_palette_4_grayscale.png interlaced_rgb_8_should_be_palette_4_grayscale.png
cp rgb_16_should_be_palette_2_grayscale.png interlaced_rgb_16_should_be_palette_2_grayscale.png
cp rgb_8_should_be_palette_2_grayscale.png interlaced_rgb_8_should_be_palette_2_grayscale.png
cp rgb_16_should_be_palette_1_grayscale.png interlaced_rgb_16_should_be_palette_1_grayscale.png
cp rgb_8_should_be_palette_1_grayscale.png interlaced_rgb_8_should_be_palette_1_grayscale.png
cp palette_8_should_be_grayscale_8.png interlaced_palette_8_should_be_grayscale_8.png
cp palette_8_should_be_palette_8.png interlaced_palette_8_should_be_palette_8.png
cp palette_8_should_be_palette_4.png interlaced_palette_8_should_be_palette_4.png
cp palette_4_should_be_palette_4.png interlaced_palette_4_should_be_palette_4.png
cp palette_8_should_be_palette_2.png interlaced_palette_8_should_be_palette_2.png
cp palette_4_should_be_palette_2.png interlaced_palette_4_should_be_palette_2.png
cp palette_2_should_be_palette_2.png interlaced_palette_2_should_be_palette_2.png
cp palette_8_should_be_palette_1.png interlaced_palette_8_should_be_palette_1.png
cp palette_4_should_be_palette_1.png interlaced_palette_4_should_be_palette_1.png
cp palette_2_should_be_palette_1.png interlaced_palette_2_should_be_palette_1.png
cp palette_1_should_be_palette_1.png interlaced_palette_1_should_be_palette_1.png
cp grayscale_alpha_16_should_be_grayscale_alpha_16.png interlaced_grayscale_alpha_16_should_be_grayscale_alpha_16.png
cp grayscale_alpha_16_should_be_grayscale_alpha_8.png interlaced_grayscale_alpha_16_should_be_grayscale_alpha_8.png
cp grayscale_alpha_8_should_be_grayscale_alpha_8.png interlaced_grayscale_alpha_8_should_be_grayscale_alpha_8.png
cp grayscale_alpha_16_should_be_grayscale_16.png interlaced_grayscale_alpha_16_should_be_grayscale_16.png
cp grayscale_alpha_16_should_be_grayscale_8.png interlaced_grayscale_alpha_16_should_be_grayscale_8.png
cp grayscale_alpha_8_should_be_grayscale_8.png interlaced_grayscale_alpha_8_should_be_grayscale_8.png
cp grayscale_alpha_16_should_be_palette_4.png interlaced_grayscale_alpha_16_should_be_palette_4.png
cp grayscale_alpha_8_should_be_palette_4.png interlaced_grayscale_alpha_8_should_be_palette_4.png
cp grayscale_alpha_16_should_be_palette_2.png interlaced_grayscale_alpha_16_should_be_palette_2.png
cp grayscale_alpha_8_should_be_palette_2.png interlaced_grayscale_alpha_8_should_be_palette_2.png
cp grayscale_alpha_16_should_be_palette_1.png interlaced_grayscale_alpha_16_should_be_palette_1.png
cp grayscale_alpha_8_should_be_palette_1.png interlaced_grayscale_alpha_8_should_be_palette_1.png
cp grayscale_16_should_be_grayscale_16.png interlaced_grayscale_16_should_be_grayscale_16.png
cp grayscale_16_should_be_grayscale_8.png interlaced_grayscale_16_should_be_grayscale_8.png
cp grayscale_16_should_be_palette_4.png interlaced_grayscale_16_should_be_palette_4.png
cp grayscale_16_should_be_palette_2.png interlaced_grayscale_16_should_be_palette_2.png
cp grayscale_16_should_be_palette_1.png interlaced_grayscale_16_should_be_palette_1.png
cp grayscale_8_should_be_grayscale_8.png interlaced_grayscale_8_should_be_grayscale_8.png
cp grayscale_8_should_be_palette_4.png interlaced_grayscale_8_should_be_palette_4.png
cp grayscale_8_should_be_palette_2.png interlaced_grayscale_8_should_be_palette_2.png
cp grayscale_8_should_be_palette_1.png interlaced_grayscale_8_should_be_palette_1.png
optipng -nx -i 1 interlaced_rgba_16_should_be_rgba_16.png
optipng -nx -i 1 interlaced_rgba_16_should_be_rgba_8.png
optipng -nx -i 1 interlaced_rgba_8_should_be_rgba_8.png
optipng -nx -i 1 interlaced_rgba_16_should_be_rgb_16.png
optipng -nx -i 1 interlaced_rgba_16_should_be_rgb_8.png
optipng -nx -i 1 interlaced_rgba_8_should_be_rgb_8.png
optipng -nx -i 1 interlaced_rgba_16_should_be_palette_8.png
optipng -nx -i 1 interlaced_rgba_8_should_be_palette_8.png
optipng -nx -i 1 interlaced_rgba_16_should_be_palette_4.png
optipng -nx -i 1 interlaced_rgba_8_should_be_palette_4.png
optipng -nx -i 1 interlaced_rgba_16_should_be_palette_2.png
optipng -nx -i 1 interlaced_rgba_8_should_be_palette_2.png
optipng -nx -i 1 interlaced_rgba_16_should_be_palette_1.png
optipng -nx -i 1 interlaced_rgba_8_should_be_palette_1.png
optipng -nx -i 1 interlaced_rgba_16_should_be_grayscale_alpha_16.png
optipng -nx -i 1 interlaced_rgba_16_should_be_grayscale_alpha_8.png
optipng -nx -i 1 interlaced_rgba_8_should_be_grayscale_alpha_8.png
optipng -nx -i 1 interlaced_rgba_16_should_be_grayscale_16.png
optipng -nx -i 1 interlaced_rgba_16_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_rgba_8_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_rgba_16_should_be_palette_4_grayscale.png
optipng -nx -i 1 interlaced_rgba_8_should_be_palette_4_grayscale.png
optipng -nx -i 1 interlaced_rgba_16_should_be_palette_2_grayscale.png
optipng -nx -i 1 interlaced_rgba_8_should_be_palette_2_grayscale.png
optipng -nx -i 1 interlaced_rgba_16_should_be_palette_1_grayscale.png
optipng -nx -i 1 interlaced_rgba_8_should_be_palette_1_grayscale.png
optipng -nx -i 1 interlaced_rgb_16_should_be_rgb_16.png
optipng -nx -i 1 interlaced_rgb_16_should_be_rgb_8.png
optipng -nx -i 1 interlaced_rgb_8_should_be_rgb_8.png
optipng -nx -i 1 interlaced_rgb_16_should_be_palette_8.png
optipng -nx -i 1 interlaced_rgb_8_should_be_palette_8.png
optipng -nx -i 1 interlaced_rgb_16_should_be_palette_4.png
optipng -nx -i 1 interlaced_rgb_8_should_be_palette_4.png
optipng -nx -i 1 interlaced_rgb_16_should_be_palette_2.png
optipng -nx -i 1 interlaced_rgb_8_should_be_palette_2.png
optipng -nx -i 1 interlaced_rgb_16_should_be_palette_1.png
optipng -nx -i 1 interlaced_rgb_8_should_be_palette_1.png
optipng -nx -i 1 interlaced_rgb_16_should_be_grayscale_16.png
optipng -nx -i 1 interlaced_rgb_16_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_rgb_8_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_rgb_16_should_be_palette_4_grayscale.png
optipng -nx -i 1 interlaced_rgb_8_should_be_palette_4_grayscale.png
optipng -nx -i 1 interlaced_rgb_16_should_be_palette_2_grayscale.png
optipng -nx -i 1 interlaced_rgb_8_should_be_palette_2_grayscale.png
optipng -nx -i 1 interlaced_rgb_16_should_be_palette_1_grayscale.png
optipng -nx -i 1 interlaced_rgb_8_should_be_palette_1_grayscale.png
optipng -nx -i 1 interlaced_palette_8_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_palette_8_should_be_palette_8.png
optipng -nx -i 1 interlaced_palette_8_should_be_palette_4.png
optipng -nx -i 1 interlaced_palette_4_should_be_palette_4.png
optipng -nx -i 1 interlaced_palette_8_should_be_palette_2.png
optipng -nx -i 1 interlaced_palette_4_should_be_palette_2.png
optipng -nx -i 1 interlaced_palette_2_should_be_palette_2.png
optipng -nx -i 1 interlaced_palette_8_should_be_palette_1.png
optipng -nx -i 1 interlaced_palette_4_should_be_palette_1.png
optipng -nx -i 1 interlaced_palette_2_should_be_palette_1.png
optipng -nx -i 1 interlaced_palette_1_should_be_palette_1.png
optipng -nx -i 1 interlaced_grayscale_alpha_16_should_be_grayscale_alpha_16.png
optipng -nx -i 1 interlaced_grayscale_alpha_16_should_be_grayscale_alpha_8.png
optipng -nx -i 1 interlaced_grayscale_alpha_8_should_be_grayscale_alpha_8.png
optipng -nx -i 1 interlaced_grayscale_alpha_16_should_be_grayscale_16.png
optipng -nx -i 1 interlaced_grayscale_alpha_16_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_grayscale_alpha_8_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_grayscale_alpha_16_should_be_palette_4.png
optipng -nx -i 1 interlaced_grayscale_alpha_8_should_be_palette_4.png
optipng -nx -i 1 interlaced_grayscale_alpha_16_should_be_palette_2.png
optipng -nx -i 1 interlaced_grayscale_alpha_8_should_be_palette_2.png
optipng -nx -i 1 interlaced_grayscale_alpha_16_should_be_palette_1.png
optipng -nx -i 1 interlaced_grayscale_alpha_8_should_be_palette_1.png
optipng -nx -i 1 interlaced_grayscale_16_should_be_grayscale_16.png
optipng -nx -i 1 interlaced_grayscale_16_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_grayscale_16_should_be_palette_4.png
optipng -nx -i 1 interlaced_grayscale_16_should_be_palette_2.png
optipng -nx -i 1 interlaced_grayscale_16_should_be_palette_1.png
optipng -nx -i 1 interlaced_grayscale_8_should_be_grayscale_8.png
optipng -nx -i 1 interlaced_grayscale_8_should_be_palette_4.png
optipng -nx -i 1 interlaced_grayscale_8_should_be_palette_2.png
optipng -nx -i 1 interlaced_grayscale_8_should_be_palette_1.png
